project_name: youtubedr

env:
  # Build without CGO to don't depend on specific glibc versions
  - CGO_ENABLED=0

builds:
  - main: ./cmd/youtubedr
    binary: youtubedr
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
